### ISSUE TITLE
Organisation of files

### ISSUE THREAD

**Issue by tony-stone** [UCL-ECHILD/docs.echild.ac.uk-website#13]
Currently it is not possible to arrange source files in the web_source directory into the order they appear in their parts/sections.

Could use:

- sub-directories; or
- prefixes in an specified form.

And create a script which moves the files into-, or renames the files in- the web_source directory. 
 
⚠️ Need to be mindful of duplicate file names.

**Comment by matthewjay15** [comment]
I was only thinking if it was an easy solution. This looks like adding an extra step (+ risk of it breaking) for only minor additional convenience. The website isn't enormous, after all.

**Comment by matthewjay15** [comment]
Is this a live issue anymore? I don't think anything more complex than what we have at the moment is needed.

**Comment by echild-admin** [comment]
Happy to close if everyone is happy with current structure. I am.

**Comment by tony-stone** [comment]
Happy to close this if the current structure works for everyone. It works for me 👍

**Comment by matthewjay15** [comment]
Therefore closed :)
