### ISSUE TITLE
CLA child ID to UPN/PMR linkage start year

### ISSUE THREAD

**Issue by tony-stone** [UCL-ECHILD/docs.echild.ac.uk-website#30]
On different pages we suggest CLA child ID to UPN/PMR linkage began in [April 2005](https://github.com/UCL-ECHILD/docs.echild.ac.uk-website/blob/8739bd856914751b6b4cb9b20c1676f354b53784/web_source/npd.qmd#L60) or [April 2006](https://github.com/UCL-ECHILD/docs.echild.ac.uk-website/blob/8739bd856914751b6b4cb9b20c1676f354b53784/web_source/data-coverage.qmd#L17). Which should it be?

Sorry @matthewjay15, I thought you the person most likely to know which was correct without needing to check.

**Comment by matthewjay15** [comment]
It's 1 April 2005 (and actually 1 October 2008 for CiN).

**Comment by tony-stone** [comment]
#39 also fixed this, CiN year.
