### ISSUE TITLE
Implement a `dev` branch and workflow

### ISSUE THREAD

**Issue by tony-stone** [UCL-ECHILD/docs.echild.ac.uk-website#32]
We should probably manage PRs through a (protected) `dev` branch. Then PR `dev` onto `main` as a **release**.

**WHY?** 
`Main` is published as the docs.echild.ac.uk website. As we transition to the docs website being the authoritative guidance, we really only want to update the website as a _fully-fledged_ release (with due approval process [inc. change log]).

**Comment by echild-admin** [comment]
Such a workflow is outdated. Instead public updates have been configured to be based on releases. Implemented by #74.
