### ISSUE TITLE
NPD user guide

### ISSUE THREAD

**Issue by matthewjay15** [UCL-ECHILD/docs.echild.ac.uk-website#41]
We should probably stop citing the 2015 NPD user guide (http://doc.ukdataservice.ac.uk/doc/7627/mrdoc/pdf/7627userguide_2015.pdf). Currently (and in the next update) referenced on the NPD page to support the statement that private school children appear in KS4. This is oversimplified but I'm struggling to find up-to-date documentation on it right now.

**Comment by matthewjay15** [comment]
Re KS4 exams and independent schools, there is some reference to independent schools at the following page, though I'm struggling to find an explicit statement that children in them sit GCSEs: https://explore-education-statistics.service.gov.uk/methodology/key-stage-4-performance-methodology

I do recall something about iGCSEs not being included and that children in independent schools are more likely to sit these. It would be good to get an opinion and more definitive answer and reference from someone more familiar with the exams data than me.

**Comment by tony-stone** [comment]
Unfortunately, the 2015 guidance is probably the best available even with its flaws (not least its age).

**Comment by matthewjay15** [comment]
Closed - agree
